[package]
name = "muddy_rpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.4", features = ["full"] }
bytes = { version = "1.1.0" }
nalgebra = { version = "0.31.0"}